# Generated by Django 6.0.3 on 2026-06-08 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CleaningTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('room', models.CharField(choices=[('kitchen', 'Кухня'), ('bathroom', 'Ванная'), ('living', 'Гостиная'), ('bedroom', 'Спальня'), ('hallway', 'Прихожая'), ('other', 'Другое')], max_length=100)),
                ('frequency', models.CharField(choices=[('daily', 'Ежедневно'), ('weekly', 'Еженедельно'), ('monthly', 'Ежемесячно'), ('seasonal', 'Сезонно'), ('yearly', 'Ежегодно')], max_length=50)),
                ('estimated_minutes', models.PositiveIntegerField(default=30)),
                ('order', models.PositiveIntegerField(default=0)),
                ('icon', models.CharField(default='fa-broom', max_length=50)),
            ],
            options={
                'verbose_name': 'Задача по уборке',
                'verbose_name_plural': 'Задачи по уборке',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='CleaningTip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='cleaning_tips/')),
                ('category', models.CharField(choices=[('stains', 'Выведение пятен'), ('organization', 'Организация'), ('tools', 'Средства и инструменты'), ('hacks', 'Лайфхаки')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
