# Generated by Django 6.0.3 on 2026-06-08 12:54

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CookingMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('category', models.CharField(choices=[('thermal', 'Тепловая обработка'), ('preparation', 'Подготовка продуктов'), ('shaping', 'Формование'), ('other', 'Прочее')], default='thermal', max_length=20, verbose_name='Категория')),
                ('short_description', models.CharField(max_length=200, verbose_name='Краткое описание')),
                ('description', models.TextField(verbose_name='Подробное описание')),
                ('scientific_background', models.TextField(blank=True, verbose_name='Научное обоснование')),
                ('typical_temperature', models.CharField(blank=True, max_length=50, verbose_name='Типичная температура')),
                ('typical_duration', models.CharField(blank=True, max_length=50, verbose_name='Типичная длительность')),
                ('tips', models.TextField(blank=True, verbose_name='Советы')),
                ('common_mistakes', models.TextField(blank=True, verbose_name='Типичные ошибки')),
                ('advanced_notes', models.TextField(blank=True, verbose_name='Для опытных')),
                ('icon', models.CharField(default='fa-fire', max_length=50, verbose_name='Иконка')),
                ('color', models.CharField(default='amber', max_length=20, verbose_name='Цвет')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Метод приготовления',
                'verbose_name_plural': 'Методы приготовления',
            },
        ),
        migrations.CreateModel(
            name='Cuisine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('region', models.CharField(blank=True, max_length=100, verbose_name='Регион')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('traditions', models.TextField(blank=True, verbose_name='Традиции')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Кухня мира',
                'verbose_name_plural': 'Кухни мира',
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('default_unit', models.CharField(choices=[('г', 'грамм'), ('кг', 'килограмм'), ('мл', 'миллилитр'), ('л', 'литр'), ('шт', 'штука'), ('ст.л.', 'столовая ложка'), ('ч.л.', 'чайная ложка'), ('щеп.', 'щепотка')], default='г', max_length=20, verbose_name='Единица измерения')),
                ('calories_per_100g', models.IntegerField(default=0, verbose_name='Калории (ккал на 100г)')),
                ('protein_per_100g', models.FloatField(default=0, verbose_name='Белки (г на 100г)')),
                ('fat_per_100g', models.FloatField(default=0, verbose_name='Жиры (г на 100г)')),
                ('carbs_per_100g', models.FloatField(default=0, verbose_name='Углеводы (г на 100г)')),
                ('season_start', models.IntegerField(blank=True, null=True, verbose_name='Начало сезона (месяц)')),
                ('season_end', models.IntegerField(blank=True, null=True, verbose_name='Конец сезона (месяц)')),
                ('storage_conditions', models.TextField(blank=True, verbose_name='Условия хранения')),
                ('shelf_life_days', models.IntegerField(default=7, verbose_name='Срок хранения (дни)')),
                ('allergens', models.JSONField(blank=True, default=list, verbose_name='Аллергены')),
                ('density_data', models.JSONField(blank=True, default=dict, verbose_name='Плотность')),
                ('is_common', models.BooleanField(default=False, verbose_name='Часто используемый')),
                ('is_vegetarian', models.BooleanField(default=True, verbose_name='Вегетарианский')),
                ('is_vegan', models.BooleanField(default=True, verbose_name='Веганский')),
                ('is_gluten_free', models.BooleanField(default=True, verbose_name='Без глютена')),
                ('image', models.ImageField(blank=True, null=True, upload_to='ingredients/', verbose_name='Изображение')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ингредиент',
                'verbose_name_plural': 'Ингредиенты',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='IngredientPreparation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='preparations/', verbose_name='Изображение')),
                ('video_url', models.URLField(blank=True, verbose_name='Видео')),
                ('time_factor', models.FloatField(default=1.0, verbose_name='Коэффициент времени')),
                ('waste_percentage', models.FloatField(default=0, verbose_name='Процент отходов')),
                ('tips', models.TextField(blank=True, verbose_name='Советы')),
            ],
            options={
                'verbose_name': 'Подготовка продукта',
                'verbose_name_plural': 'Подготовка продуктов',
            },
        ),
        migrations.CreateModel(
            name='RecommendedUtensil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='utensils/', verbose_name='Изображение')),
                ('alternative', models.CharField(blank=True, max_length=200, verbose_name='Чем заменить')),
                ('care_instructions', models.TextField(blank=True, verbose_name='Уход')),
            ],
            options={
                'verbose_name': 'Утварь',
                'verbose_name_plural': 'Утварь',
            },
        ),
        migrations.CreateModel(
            name='Diet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('authority', models.CharField(blank=True, max_length=200, verbose_name='Утвердивший орган')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('allowed_methods', models.TextField(blank=True, verbose_name='Разрешённые методы приготовления')),
                ('nutritional_guidelines', models.TextField(blank=True, verbose_name='Нормы КБЖУ')),
                ('medical_indications', models.TextField(blank=True, verbose_name='Медицинские показания')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('allowed_ingredients', models.ManyToManyField(blank=True, related_name='allowed_for_diets', to='kitchen.ingredient')),
                ('prohibited_ingredients', models.ManyToManyField(blank=True, related_name='prohibited_for_diets', to='kitchen.ingredient')),
            ],
            options={
                'verbose_name': 'Диета',
                'verbose_name_plural': 'Диеты',
            },
        ),
        migrations.CreateModel(
            name='IngredientCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='Иконка')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Порядок сортировки')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategories', to='kitchen.ingredientcategory', verbose_name='Родительская категория')),
            ],
            options={
                'verbose_name': 'Категория ингредиентов',
                'verbose_name_plural': 'Категории ингредиентов',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='ingredient',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingredients', to='kitchen.ingredientcategory', verbose_name='Категория'),
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('author', models.CharField(blank=True, max_length=100, verbose_name='Автор')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('total_time', models.IntegerField(default=0, verbose_name='Время приготовления (мин)')),
                ('servings', models.IntegerField(default=4, verbose_name='Порций')),
                ('difficulty', models.CharField(choices=[('easy', 'Лёгкий'), ('medium', 'Средний'), ('hard', 'Сложный')], default='medium', max_length=10, verbose_name='Сложность')),
                ('is_professional', models.BooleanField(default=False, verbose_name='Профессиональный')),
                ('image', models.ImageField(blank=True, null=True, upload_to='recipes/', verbose_name='Изображение')),
                ('video', models.URLField(blank=True, verbose_name='Видео')),
                ('calories', models.IntegerField(default=0, verbose_name='Калории')),
                ('protein', models.IntegerField(default=0, verbose_name='Белки')),
                ('fat', models.IntegerField(default=0, verbose_name='Жиры')),
                ('carbs', models.IntegerField(default=0, verbose_name='Углеводы')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('components', models.ManyToManyField(blank=True, related_name='parent_recipes', to='kitchen.recipe', verbose_name='Компоненты блюда')),
                ('cuisine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kitchen.cuisine', verbose_name='Кухня')),
                ('diet_tags', models.ManyToManyField(blank=True, to='kitchen.diet', verbose_name='Диеты')),
                ('related_recipes', models.ManyToManyField(blank=True, to='kitchen.recipe', verbose_name='Связанные рецепты')),
            ],
            options={
                'verbose_name': 'Рецепт',
                'verbose_name_plural': 'Рецепты',
            },
        ),
        migrations.CreateModel(
            name='ProfessionalIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gross_weight', models.DecimalField(decimal_places=2, help_text='Например, 150г неочищенного лука', max_digits=8, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Брутто (вес с отходами)')),
                ('net_weight', models.DecimalField(decimal_places=2, help_text='Например, 120г очищенного лука', max_digits=8, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Нетто (чистый вес)')),
                ('unit', models.CharField(choices=[('г', 'грамм'), ('кг', 'килограмм'), ('мл', 'миллилитр'), ('л', 'литр'), ('шт', 'штука'), ('ст.л.', 'столовая ложка'), ('ч.л.', 'чайная ложка'), ('щеп.', 'щепотка')], default='г', max_length=10, verbose_name='Единица измерения')),
                ('loss_factor', models.DecimalField(blank=True, decimal_places=3, help_text='Обычно рассчитывается как gross/net. Для сезонных поправок можно указать вручную', max_digits=5, null=True, verbose_name='Коэффициент потерь (брутто/нетто)')),
                ('is_base_allowed', models.BooleanField(default=True, verbose_name='Может быть базовым ингредиентом для пересчета')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kitchen.ingredient', verbose_name='Ингредиент')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pro_ingredients', to='kitchen.recipe', verbose_name='Рецепт')),
            ],
            options={
                'verbose_name': 'Ингредиент (профессиональный)',
                'verbose_name_plural': 'Ингредиенты (профессиональные)',
            },
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Количество')),
                ('unit', models.CharField(choices=[('г', 'грамм'), ('кг', 'килограмм'), ('мл', 'миллилитр'), ('л', 'литр'), ('шт', 'штука'), ('ст.л.', 'столовая ложка'), ('ч.л.', 'чайная ложка'), ('щеп.', 'щепотка')], default='г', max_length=20)),
                ('notes', models.CharField(blank=True, max_length=500)),
                ('is_scalable', models.BooleanField(default=True)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_uses', to='kitchen.ingredient')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_ingredients', to='kitchen.recipe')),
            ],
            options={
                'verbose_name': 'Ингредиент рецепта',
                'verbose_name_plural': 'Ингредиенты рецептов',
                'unique_together': {('recipe', 'ingredient')},
            },
        ),
        migrations.CreateModel(
            name='CookingMethodSubstitution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(blank=True, max_length=200, verbose_name='Причина замены')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('original_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substitutions', to='kitchen.cookingmethod', verbose_name='Исходный метод')),
                ('substitute_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='original_for', to='kitchen.cookingmethod', verbose_name='Метод-заменитель')),
            ],
            options={
                'verbose_name': 'Замена метода приготовления',
                'verbose_name_plural': 'Замены методов приготовления',
                'unique_together': {('original_method', 'substitute_method')},
            },
        ),
        migrations.CreateModel(
            name='IngredientSubstitution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('substitute_unit', models.CharField(choices=[('г', 'грамм'), ('кг', 'килограмм'), ('мл', 'миллилитр'), ('л', 'литр'), ('шт', 'штука'), ('ст.л.', 'столовая ложка'), ('ч.л.', 'чайная ложка'), ('щеп.', 'щепотка')], max_length=20, verbose_name='Единица измерения заменителя')),
                ('ratio', models.FloatField(default=1.0, help_text='Например: 1 ст.л. пасты = 2 ст.л. помидоров', verbose_name='Коэффициент пересчёта')),
                ('notes', models.CharField(blank=True, max_length=500, verbose_name='Примечания по замене')),
                ('substitute_ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substitutions', to='kitchen.ingredient', verbose_name='Ингредиент-заменитель')),
                ('recipe_ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substitutions', to='kitchen.recipeingredient', verbose_name='Исходный ингредиент в рецепте')),
            ],
            options={
                'verbose_name': 'Допустимая замена',
                'verbose_name_plural': 'Допустимые замены',
                'unique_together': {('recipe_ingredient', 'substitute_ingredient')},
            },
        ),
        migrations.CreateModel(
            name='RecipeStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(verbose_name='Порядок')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('instruction', models.TextField(verbose_name='Инструкция')),
                ('duration', models.IntegerField(default=0, verbose_name='Длительность (мин)')),
                ('temperature', models.IntegerField(blank=True, null=True, verbose_name='Температура')),
                ('subrecipe_base_quantity', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Количество базового ингредиента')),
                ('cooking_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='steps', to='kitchen.cookingmethod', verbose_name='Метод приготовления')),
                ('ingredient_preparation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='steps', to='kitchen.ingredientpreparation', verbose_name='Подготовка продуктов')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='kitchen.recipe')),
                ('subrecipe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_in_steps', to='kitchen.recipe', verbose_name='Вложенный рецепт')),
                ('subrecipe_base_ingredient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='base_for_steps', to='kitchen.recipeingredient', verbose_name='Базовый ингредиент из вложенного рецепта')),
                ('recommended_utensils', models.ManyToManyField(blank=True, related_name='steps', to='kitchen.recommendedutensil', verbose_name='Рекомендованная утварь')),
            ],
            options={
                'verbose_name': 'Шаг приготовления',
                'verbose_name_plural': 'Шаги приготовления',
                'ordering': ['order'],
                'constraints': [models.UniqueConstraint(fields=('recipe', 'order'), name='unique_recipe_step_order')],
            },
        ),
        migrations.CreateModel(
            name='UtensilSubstitution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(blank=True, max_length=200, verbose_name='Причина замены')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('original_utensil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substitutions', to='kitchen.recommendedutensil', verbose_name='Исходная утварь')),
                ('substitute_utensil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='original_for', to='kitchen.recommendedutensil', verbose_name='Утварь-заменитель')),
            ],
            options={
                'verbose_name': 'Замена утвари',
                'verbose_name_plural': 'Замены утвари',
                'unique_together': {('original_utensil', 'substitute_utensil')},
            },
        ),
    ]
