# Generated by Django 6.0.3 on 2026-05-31 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('cooking_time', models.IntegerField(verbose_name='Время приготовления (мин)')),
                ('difficulty', models.CharField(choices=[('easy', 'Лёгкий'), ('medium', 'Средний'), ('hard', 'Сложный')], default='medium', max_length=20, verbose_name='Сложность')),
                ('servings', models.IntegerField(default=4, verbose_name='Порций')),
                ('calories', models.IntegerField(default=0, verbose_name='Калории')),
                ('protein', models.IntegerField(default=0, verbose_name='Белки')),
                ('fat', models.IntegerField(default=0, verbose_name='Жиры')),
                ('carbs', models.IntegerField(default=0, verbose_name='Углеводы')),
                ('image', models.ImageField(upload_to='recipes/original/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Рецепт',
                'verbose_name_plural': 'Рецепты',
            },
        ),
    ]
