# Generated by Django 6.0.3 on 2026-06-01 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CookingMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('category', models.CharField(choices=[('thermal', 'Тепловая обработка'), ('preparation', 'Подготовка продуктов'), ('shaping', 'Формование'), ('other', 'Прочее')], default='thermal', max_length=20)),
                ('short_description', models.CharField(max_length=200, verbose_name='Краткое описание')),
                ('description', models.TextField(verbose_name='Подробное описание техники')),
                ('scientific_background', models.TextField(blank=True, verbose_name='Научное обоснование')),
                ('typical_temperature', models.CharField(blank=True, max_length=50, verbose_name='Типичная температура')),
                ('typical_duration', models.CharField(blank=True, max_length=50, verbose_name='Типичная длительность')),
                ('tips', models.TextField(blank=True, verbose_name='Советы и хитрости')),
                ('common_mistakes', models.TextField(blank=True, verbose_name='Типичные ошибки')),
                ('icon', models.CharField(default='fa-fire', max_length=50, verbose_name='Иконка (FontAwesome)')),
                ('color', models.CharField(default='amber', max_length=20, verbose_name='Цвет темы')),
                ('advanced_notes', models.TextField(blank=True, verbose_name='Для опытных кулинаров')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Метод приготовления',
                'verbose_name_plural': 'Методы приготовления',
            },
        ),
        migrations.CreateModel(
            name='IngredientPreparation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='preparations/')),
                ('video_url', models.URLField(blank=True)),
                ('time_factor', models.FloatField(default=1.0, help_text='Коэффициент увеличения времени')),
                ('tips', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='RecommendedUtensil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='utensils/')),
                ('alternative', models.CharField(blank=True, help_text='Чем можно заменить', max_length=200)),
                ('care_instructions', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='RecipeStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('title', models.CharField(max_length=200)),
                ('instruction', models.TextField(blank=True)),
                ('subrecipe_usage', models.CharField(blank=True, help_text="Что сделать с приготовленным блюдом (например: 'добавить соус в фарш')", max_length=500)),
                ('duration', models.IntegerField(default=0, help_text='Длительность шага в минутах')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='kitchen.recipe')),
                ('subrecipe', models.ForeignKey(blank=True, help_text='Рецепт, который нужно приготовить внутри этого шага', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_in_steps', to='kitchen.recipe')),
            ],
        ),
    ]
