# Generated by Django 6.0.3 on 2026-06-01 13:16

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0002_cookingmethod_ingredientpreparation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuisine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('region', models.CharField(blank=True, max_length=100, verbose_name='Регион')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('traditions', models.TextField(blank=True, verbose_name='Традиции')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Кухня мира',
                'verbose_name_plural': 'Кухни мира',
            },
        ),
        migrations.CreateModel(
            name='Diet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('authority', models.CharField(blank=True, max_length=200, verbose_name='Утвердивший орган')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('allowed_methods', models.TextField(blank=True, verbose_name='Разрешённые методы приготовления')),
                ('nutritional_guidelines', models.TextField(blank=True, verbose_name='Нормы КБЖУ')),
                ('medical_indications', models.TextField(blank=True, verbose_name='Медицинские показания')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Диета',
                'verbose_name_plural': 'Диеты',
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('default_unit', models.CharField(choices=[('г', 'грамм'), ('кг', 'килограмм'), ('мл', 'миллилитр'), ('л', 'литр'), ('шт', 'штука'), ('ст.л.', 'столовая ложка'), ('ч.л.', 'чайная ложка'), ('щеп.', 'щепотка')], default='г', max_length=20, verbose_name='Единица измерения')),
                ('calories_per_100g', models.IntegerField(default=0, verbose_name='Калории (ккал на 100г)')),
                ('protein_per_100g', models.FloatField(default=0, verbose_name='Белки (г на 100г)')),
                ('fat_per_100g', models.FloatField(default=0, verbose_name='Жиры (г на 100г)')),
                ('carbs_per_100g', models.FloatField(default=0, verbose_name='Углеводы (г на 100г)')),
                ('season_start', models.IntegerField(blank=True, null=True, verbose_name='Начало сезона (месяц)')),
                ('season_end', models.IntegerField(blank=True, null=True, verbose_name='Конец сезона (месяц)')),
                ('storage_conditions', models.TextField(blank=True, verbose_name='Условия хранения')),
                ('shelf_life_days', models.IntegerField(default=7, verbose_name='Срок хранения (дни)')),
                ('allergens', models.JSONField(blank=True, default=list, verbose_name='Аллергены')),
                ('density_data', models.JSONField(blank=True, default=dict, verbose_name='Плотность')),
                ('is_common', models.BooleanField(default=False, verbose_name='Часто используемый')),
                ('is_vegetarian', models.BooleanField(default=True, verbose_name='Вегетарианский')),
                ('is_vegan', models.BooleanField(default=True, verbose_name='Веганский')),
                ('is_gluten_free', models.BooleanField(default=True, verbose_name='Без глютена')),
                ('image', models.ImageField(blank=True, null=True, upload_to='ingredients/', verbose_name='Изображение')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ингредиент',
                'verbose_name_plural': 'Ингредиенты',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='ingredientpreparation',
            options={'verbose_name': 'Подготовка продукта', 'verbose_name_plural': 'Подготовка продуктов'},
        ),
        migrations.AlterModelOptions(
            name='recipestep',
            options={'ordering': ['order'], 'verbose_name': 'Шаг приготовления', 'verbose_name_plural': 'Шаги приготовления'},
        ),
        migrations.AlterModelOptions(
            name='recommendedutensil',
            options={'verbose_name': 'Утварь', 'verbose_name_plural': 'Утварь'},
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='cooking_time',
        ),
        migrations.RemoveField(
            model_name='recipestep',
            name='subrecipe_usage',
        ),
        migrations.AddField(
            model_name='ingredientpreparation',
            name='waste_percentage',
            field=models.FloatField(default=0, verbose_name='Процент отходов'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='author',
            field=models.CharField(blank=True, max_length=100, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='related_recipes',
            field=models.ManyToManyField(blank=True, to='kitchen.recipe', verbose_name='Связанные рецепты'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='total_time',
            field=models.IntegerField(default=0, verbose_name='Время приготовления (мин)'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='video',
            field=models.URLField(blank=True, verbose_name='Видео'),
        ),
        migrations.AddField(
            model_name='recipestep',
            name='temperature',
            field=models.IntegerField(blank=True, null=True, verbose_name='Температура'),
        ),
        migrations.AlterField(
            model_name='cookingmethod',
            name='advanced_notes',
            field=models.TextField(blank=True, verbose_name='Для опытных'),
        ),
        migrations.AlterField(
            model_name='cookingmethod',
            name='category',
            field=models.CharField(choices=[('thermal', 'Тепловая обработка'), ('preparation', 'Подготовка продуктов'), ('shaping', 'Формование'), ('other', 'Прочее')], default='thermal', max_length=20, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='cookingmethod',
            name='color',
            field=models.CharField(default='amber', max_length=20, verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='cookingmethod',
            name='description',
            field=models.TextField(verbose_name='Подробное описание'),
        ),
        migrations.AlterField(
            model_name='cookingmethod',
            name='icon',
            field=models.CharField(default='fa-fire', max_length=50, verbose_name='Иконка'),
        ),
        migrations.AlterField(
            model_name='cookingmethod',
            name='tips',
            field=models.TextField(blank=True, verbose_name='Советы'),
        ),
        migrations.AlterField(
            model_name='ingredientpreparation',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='ingredientpreparation',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='preparations/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='ingredientpreparation',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='ingredientpreparation',
            name='time_factor',
            field=models.FloatField(default=1.0, verbose_name='Коэффициент времени'),
        ),
        migrations.AlterField(
            model_name='ingredientpreparation',
            name='tips',
            field=models.TextField(blank=True, verbose_name='Советы'),
        ),
        migrations.AlterField(
            model_name='ingredientpreparation',
            name='video_url',
            field=models.URLField(blank=True, verbose_name='Видео'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Лёгкий'), ('medium', 'Средний'), ('hard', 'Сложный')], default='medium', max_length=10, verbose_name='Сложность'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='recipes/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='recipestep',
            name='duration',
            field=models.IntegerField(default=0, verbose_name='Длительность (мин)'),
        ),
        migrations.AlterField(
            model_name='recipestep',
            name='instruction',
            field=models.TextField(verbose_name='Инструкция'),
        ),
        migrations.AlterField(
            model_name='recipestep',
            name='order',
            field=models.IntegerField(verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='recipestep',
            name='subrecipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_in_steps', to='kitchen.recipe', verbose_name='Вложенный рецепт'),
        ),
        migrations.AlterField(
            model_name='recipestep',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='recommendedutensil',
            name='alternative',
            field=models.CharField(blank=True, max_length=200, verbose_name='Чем заменить'),
        ),
        migrations.AlterField(
            model_name='recommendedutensil',
            name='care_instructions',
            field=models.TextField(blank=True, verbose_name='Уход'),
        ),
        migrations.AlterField(
            model_name='recommendedutensil',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='recommendedutensil',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='utensils/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='recommendedutensil',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='cuisine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kitchen.cuisine', verbose_name='Кухня'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='diet_tags',
            field=models.ManyToManyField(blank=True, to='kitchen.diet', verbose_name='Диеты'),
        ),
        migrations.AddField(
            model_name='diet',
            name='allowed_ingredients',
            field=models.ManyToManyField(blank=True, related_name='allowed_for_diets', to='kitchen.ingredient'),
        ),
        migrations.AddField(
            model_name='diet',
            name='prohibited_ingredients',
            field=models.ManyToManyField(blank=True, related_name='prohibited_for_diets', to='kitchen.ingredient'),
        ),
        migrations.CreateModel(
            name='IngredientCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='Иконка')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Порядок сортировки')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategories', to='kitchen.ingredientcategory', verbose_name='Родительская категория')),
            ],
            options={
                'verbose_name': 'Категория ингредиентов',
                'verbose_name_plural': 'Категории ингредиентов',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='ingredient',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingredients', to='kitchen.ingredientcategory', verbose_name='Категория'),
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Количество')),
                ('unit', models.CharField(choices=[('г', 'грамм'), ('кг', 'килограмм'), ('мл', 'миллилитр'), ('л', 'литр'), ('шт', 'штука'), ('ст.л.', 'столовая ложка'), ('ч.л.', 'чайная ложка'), ('щеп.', 'щепотка')], default='г', max_length=20, verbose_name='Единица измерения')),
                ('notes', models.CharField(blank=True, max_length=500, verbose_name='Примечания')),
                ('is_scalable', models.BooleanField(default=True, verbose_name='Масштабируется')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_uses', to='kitchen.ingredient')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_ingredients', to='kitchen.recipe')),
            ],
            options={
                'verbose_name': 'Ингредиент рецепта',
                'verbose_name_plural': 'Ингредиенты рецептов',
                'unique_together': {('recipe', 'ingredient')},
            },
        ),
    ]
