# Generated by Django 6.0.3 on 2026-06-01 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0003_cuisine_diet_ingredient_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientSubstitution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('substitute_name', models.CharField(max_length=200, verbose_name='Название заменителя')),
                ('substitute_unit', models.CharField(choices=[('г', 'грамм'), ('кг', 'килограмм'), ('мл', 'миллилитр'), ('л', 'литр'), ('шт', 'штука'), ('ст.л.', 'столовая ложка'), ('ч.л.', 'чайная ложка'), ('щеп.', 'щепотка')], max_length=20, verbose_name='Единица измерения заменителя')),
                ('ratio', models.FloatField(default=1.0, help_text='Например: 1 ст.л. пасты = 2 ст.л. помидоров', verbose_name='Коэффициент пересчёта')),
                ('notes', models.CharField(blank=True, max_length=500, verbose_name='Примечания по замене')),
                ('recipe_ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substitutions', to='kitchen.recipeingredient', verbose_name='Исходный ингредиент в рецепте')),
            ],
            options={
                'verbose_name': 'Допустимая замена',
                'verbose_name_plural': 'Допустимые замены',
            },
        ),
    ]
